### ISSUE TITLE
2.1.0-Beta2 

### ISSUE THREAD

**Issue by gdmoney** [crocandr/docker-unimus#11]
Hi, I'm just wondering when you plan on building the beta2 image. Thanks.

**Comment by crocandr** [comment]
Hi,

Here is:
https://hub.docker.com/layers/croc/unimus/2.1.0-Beta2/images/sha256-0f4b48dfe35f34b55abf0281ea7280c20f6190a5b5911ca3fe7df2ffe9227919?context=explore

The automatic build process runs every day for DEV builds. If the version is downloadable and shows the correct version after the start (test after the build) it will appear on Docker Hub after the build.

**Comment by gdmoney** [comment]
Thank you!
