### ISSUE TITLE
Push image to alternative docker registries too (eg. Github Docker Registry, quay.io)

### ISSUE THREAD

**Issue by samip5** [crocandr/docker-unimus#15]
Hi there,

Due to the rate limits in place at hub.docker.com, I would kindly ask for this image to be pushed to alternative registries too, like Github Docker Registry, quay.io.

Otherwise when deploying a lot of containers in a close time frame, you will hit the rate limits and thus unable to pull the image.

**Comment by crocandr** [comment]
Hi,

Thank you. :)
I'm going to upload the images to an alternative registry too. I've made a first quick check for alternatives but many have limitations and pricy plans. But, I will check the options in more detail on the next weeks.

You should registry on hub.docker.com. If you pull the images after docker login you can download them anytime.
The Personal(basic/free) option is enough basic usage, but you can upgrade to Pro plan if You develop lots of containers. (https://www.docker.com/pricing) Sorry If You tried this.

**Comment by samip5** [comment]
> You should registry on hub.docker.com. If you pull the images after docker login you can download them anytime. The Personal(basic/free) option is enough basic usage, but you can upgrade to Pro plan if You develop lots of containers. (https://www.docker.com/pricing) Sorry If You tried this.

I'm sorry, but I have a user there but I don't want to be logged on in multiple different systems to it. Including Kubernetes cluster.
Even if I had the Pro plan, there's still rate limits and I don't want to pay for something like that.

>The limits will be fully enforced Monday, November 2, from 9-10 am PT, and then reduced to 5,000 pulls per 6 hours for anonymous and free users. This will briefly inform some users whether they are exceeding the limits, but allow service to resume within an hour. The limits will be gradually reduced over a number of weeks until the final levels (where anonymous users are limited to 100 container pulls per six hours and free users limited to 200 container pulls per six hours) are reached. All paid Docker accounts (Pro. Team or Legacy subscribers) have up to 50,000 pulls in a 24 hour period.
> - Source: https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/

**Comment by crocandr** [comment]
Hi,

I hope it helps: https://quay.io/repository/croc/unimus

Another idea:
If you install a Nexus3 locally (in your network), you can use it as a docker registry and/or proxy too. It can cache docker images and works without any limitation ;)

Have a nice day!
