### ISSUE TITLE
Ping missing for network scan

### ISSUE THREAD

**Issue by haakonnessjoen** [crocandr/docker-unimus#19]
Hi,

The docker container is missing the ping utility, so network scans gives a lot of these in the console:
```
ERROR 12 --- [        scan-11] net.unimus.core.service.scan.PingTester  : Native ping call failed - unable to ping '10.0.0.191'. Reason = 'Cannot run program "ping": error=2, No such file or directory; cause: error=2, No such file or directory'
```

**Comment by crocandr** [comment]
Hi,

Thank you for the ticket! :)

I have added the iputils-ping package to the container and looks like the network scan now works fine.
Pull the new, updated images from docker hub and try it again, please.

Have a nice day! :)
