### ISSUE TITLE
please add 2.0.0 dev build

### ISSUE THREAD

**Issue by philippkayser** [crocandr/docker-unimus#2]
Can you please add this build for upgrading? Because in current version there is a bug with Mikrotik Free license.

https://drive.google.com/drive/folders/1RRzpYInJzjMBkaokbDISTL00NbXxGpvD

**Comment by crocandr** [comment]
Thanks! :)

I created new images on docker hub and a new 2.0.0 branch here.

**Comment by philippkayser** [comment]
Hi @crocandr 

Thanks therefore, unfortunately the fix is not included in the latest version because it's still in dev build.
So could you please add the application from the link in my first comment? I've got it from unimus.

`Greetings,

Just wanted to provide an update:
we have now fixed this issue, and a fix is available in our latest 2.0.0 dev build.

If you wish to test this, a build is available here:
https://drive.google.com/drive/folders/1RRzpYInJzjMBkaokbDISTL00NbXxGpvD

Please read the Changelog if you deploy this build, as there is a lot of things that changed in 2.0.0.

Regards,

------------------------------------

Tomas Kirnak

Unimus team leader
https://www.unimus.net`

**Comment by crocandr** [comment]
Hi,

Sorry, I can't write a simple curl or wget command to download anything from a GoogleDrive share. I found lots of tips on the internet but not working.
Thus I downloaded the jar file manually from the share and updated the docker images (latest and 2.0.0 versions) on docker hub.

You can check like this:
```
mkdir unimus-test
curl -L -o unimus-test/docker-compose.yml https://raw.githubusercontent.com/crocandr/docker-unimus/master/docker-compose.yml
docker-compose -f unimus-test/docker-compose.yml up -d
```

`docker-compose -f unimus-test/docker-compose.yml logs unimus | grep -i version`:
```
unimus_1  | :: ? 2016-2019 NetCore j.s.a. :: version 2.0.0-alpha10 ::
```

Sorry.

Regards,
Andras

**Comment by philippkayser** [comment]
I've pulled the latest image
2016-2019 NetCore j.s.a. :: version 2.0.0-alpha8 ::

**Comment by philippkayser** [comment]
Now, I've set the tag ":latest" to compose file afterwards it's running with the alpha10, Thanks!
`unimus_1  | :: ? 2016-2019 NetCore j.s.a. :: version 2.0.0-alpha10 ::`
