### ISSUE TITLE
HSQL volume mounting issue

### ISSUE THREAD

**Issue by tomaskir** [crocandr/docker-unimus#3]
Currently documentation states to use HSQL container with:
`-e /srv/unimus/config:/etc/unimus/`

This should likely be `-v`. Currently each restart/spawn of HSQL container will lose all settings and the HSQL DB, since those are kept in `/etc/unimus` and not persisted.

**Comment by crocandr** [comment]
Thank you and sorry! I use docker-compose with MySQL and missed this mistyped character.
