### ISSUE TITLE
Older Unimus versions

### ISSUE THREAD

**Issue by tomaskir** [crocandr/docker-unimus#4]
Just an update on a download link to all older Unimus versions.
(as per the README comment)

> Sorry, you can't build an image with an older unimus version, because I don't know the download URL for an older version. 

All older Unimus version are available at http://unimus.net/download/x.x.x/Unimus.jar
For example, for 0.3.0: http://unimus.net/download/0.3.0/Unimus.jar

Versions older than 0.3.0 are not available, as they are old closed alpha/beta builds (4+ years old), and are no longer supported in any way.

Latest versions are always available at https://unimus.net/download/-%20Latest/Unimus.jar

We definitely always recommend running the latest stable version, but access to older versions is still available :)

**Comment by crocandr** [comment]
I created an example line for an older version in the Docker file and created a wiki page too (https://github.com/crocandr/docker-unimus/wiki/download-specific-versions).

Thank you for the ticket and the information.
