### ISSUE TITLE
Expose memory limit configuration

### ISSUE THREAD

**Issue by tomaskir** [crocandr/docker-unimus#6]
It would be useful to allow setting memory limitations for the Unimus container.

This is configured through the main java run command:
```
java -Xms256M -Xmx768M -jar Unimus.jar
```
Xms specifies startup memory allocation.
Xmx specifies maximum memory allocation limit.

Sizing and configuration documentations are available here:
https://wiki.unimus.net/display/UNPUB/Hardware+requirements
https://wiki.unimus.net/display/UNPUB/Configuring+memory+usage

By default, I would recommend `-Xms256M -Xmx768M`, with options for users to set higher limits if needed (things like `-Xmx2G` will work as well).

**Comment by crocandr** [comment]
Updated the docker-compose file and the container with Xms and Xms option.
If you like it, you can use more Java parameters in compose file, like permgen size, etc.

I hope it helps :)

Thanks for the ticket.
