### ISSUE TITLE
override entry point?

### ISSUE THREAD

**Issue by mtnbrit** [crocandr/docker-unimus#8]
Hi, I tried to upgrade my Unimus 1 docker running on Synology NAS, but after I restart, I only get 

```Error: Invalid or corrupt jarfile /opt/unimus.jar```

in the log and it constantly restarts.

How can I override the Entrypoint so it doesnt try to run the /opt/start.sh and then I can open a shell to fix the bad jar file?

I dont know why it failed, I did the 

```curl https://unimus.net/download/-%20Latest/Unimus.jar -o /opt/unimus.jar```

command which appeared to succeed. I do see a thread on Uniumus community about bad jar files, but it seems to have been back in April.

Any help most welcome, I dont want to lose this instance as its using the internal database....

**Comment by crocandr** [comment]
Hi,

Thanks for the issue :)

Sorry, you can't override the entrypoint without image rebuild. :(

Which type of Synology NAS do you use? Is it x86_64 based or Arm based?
You can run the unimus container on x86_64 platform only.

Maybe help:
https://www.synology.com/en-us/knowledgebase/DSM/tutorial/Compatibility_Peripherals/What_kind_of_CPU_does_my_NAS_have


But thanks, I found an another problem. The latest tag not pointed to the latest 2.x.x version.  I will fix this.

**Comment by mtnbrit** [comment]
I was able to use docker cp to copy the start.sh script out of the stopped container, edit it to include an infinite while loop, use docker cp to put it back, then I could start it without it exiting right away. Then I was able to get a shell on it and curl the file properly, fix the edits to the start.sh, and restart the container. All good now, thx.

The cause of the issue was missing -L on curl, 

See this from Tomas

> You need to use:
> curl -L https://unimus.net/download/-%20Latest/Unimus.jar <https://unimus.net/download/-%20Latest/Unimus.jar> -o /opt/unimus.jar
> 
> The link is a 301 redirect, which curl by default doesn't follow, so you end up with a few kilobyte html redirect document in " /opt/unimus.jar".
