### ISSUE TITLE
docker run command out of date

### ISSUE THREAD

**Issue by terafirmanz** [crocandr/docker-unimus#9]
Hi,

Not sure if this should be here or the forum but your example docker run command includes
`-v /srv/unimus/db:/var/unimus/hsql`
however the hsql database has been moved from /var/unimus/hsql to /etc/unimus/hsql so the second volume mount is no longer needed as the first provides both the DB and config files.

**Comment by crocandr** [comment]
Hi,

Thank you!

Sorry, I use docker-compose with MySQL and absolutely forgotten to check HSQL backend.
Thank you again and sorry for the inconvenience.

Have a nice day!
